DROP TABLE films IF EXISTS CASCADE;
DROP TABLE FILMS_GENRES IF EXISTS CASCADE;
DROP TABLE FRIENDS IF EXISTS CASCADE;
DROP TABLE GENRES IF EXISTS CASCADE;
DROP TABLE LIKES IF EXISTS CASCADE;
DROP TABLE RATING IF EXISTS CASCADE;
DROP TABLE USERS IF EXISTS CASCADE;